<?php

error_reporting(0);

$timezone = "Asia/Jakarta";
if(function_exists(date_default_timezone_set)) date_default_timezone_set($timezone);

session_start();
if (empty($_SESSION[username]) AND empty($_SESSION[passuser])){
  echo "<link href=style.css rel=stylesheet type=text/css>
 <center>Untuk mengakses modul, Anda harus login <br>";
  echo "<a href=../../index.php><b>LOGIN</b></a></center>";
}
else{
error_reporting(0);
include "../../plugin/mpdf/mpdf.php";
include "../../config/koneksi.php";

ob_start();

/*
$nama 	= mysqli_query($GLOBALS["___mysqli_ston"], "SELECT * from nama WHERE id_nama=1 ");
$tnama	= mysqli_fetch_array($nama);

$kue	= mysqli_query($GLOBALS["___mysqli_ston"], "Select * from smasuk a left join jenis b on a.jSurat=b.kodejenis where id_sMasuk=$_GET[id]");
$h		= mysqli_fetch_array($kue);

$jab3	= mysqli_query($GLOBALS["___mysqli_ston"], "select jabatan from rjabatan where left(eselon,1)='3' ");
$jab4	= mysqli_query($GLOBALS["___mysqli_ston"], "select jabatan from rjabatan where left(eselon,1)='4' ");
*/

echo '
	<html>
	<head><title></title>
		<style type="text/css">
	p{
		text-align:left;
		font-size:7px;
		font-family:"Arial, Helvetica, sans-serif;
		color:#000066;
	}
	body{
		font-size:12px;
		font-family:"Arial, Helvetica, sans-serif;
	}

	table{
		border-style:solid;
		border-width:thin;
		border-spacing:inherit;
	}



	</style>

	</head>
	<body>
	<table width="100%" cellspacing="0">
	<tr><td rowspan="6" width="15%" align=center><img src="../../images/logo-keu.jpg" width="75px" height="60px" ></img></td>
	<td align=center width="85%" style="font-size:16px;">Kementerian</td></tr>
	<tr><td align=center style="font-size:14px;">Eselon I</td></tr>
	<tr><td align=center style="font-size:14px;">Eselon 2</td></tr>
	<tr><td align=center style="font-size:12px;">Eselon III</td></tr>
	<tr><td align=center style="font-size:9px;">Eselon IV </td></tr>
	<tr><td align=center style="font-size:9px;"> Telpon:telp Email: mail Website:web</td></tr>
	</table>

	<table width="100%" cellspacing="0">
	<tr><td align=center bgcolor=black style="font-weight:bold; color:#ffffff; font-size:12px;">LEMBAR DISPOSISI nama</td></tr>
	</table>';


echo '
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<b><u>CATATAN:</u></b>
	</td>
	<td valign=top>
	<br/>';

echo '
	<br/>
	<b>[  ] PEJABAT/UNIT LAIN</b>
	</td>
	<td>
	<br/>
	<b>PETUNJUK:</b><br/>
	[  ] Setuju sesuai dgn ketentuan yang berlaku <br/>
	[  ] Tolak sesuai dgn ketentuan yang berlaku <br/>
	[  ] Selesaikan sesuai dgn ketentuan yang berlaku <br/>
	[  ] Jawab sesuai dgn ketentuan yang berlaku <br/>
	[  ] Perbaiki sesuai dgn ketentuan yang berlaku <br/>
	[  ] Teliti dan Pendapat <br/>
	[  ] Sesuai catatan <br/>
	[  ] Untuk perhatian <br/>
	[  ] Untuk diketahui <br/>
	[  ] Edarkan <br/>
	[  ] Bicarakan dengan saya <br/>
	[  ] Bicarakan bersama dan laporkan hasilnya <br/>
	[  ] Dijadwalkan <br/>
	[  ] Disimpan <br/>
	[  ] Disiapkan <br/>
	[  ] Ingatkan <br/>
	[  ] Harap dihadiri/ diwakili <br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	<br/>
	</td>
	</tr>
	</table>

	<table width="100%" cellspacing="0" cellpadding="7">
	<tr><td width="50%" align=left style="border-width:thin; border-right-style:solid; border-bottom-style:solid;"><font size="10pt">Tgl dikirim untuk proses: <br/>Diterima Oleh:<br/><br/><br/><br/><br/><br/></font></td>
	<td width="50%" align=left style="border-width:thin; border-bottom-style:solid;"><font size="10pt">Diajukan kembali tanggal: <br/>Diterima Oleh:<br/><br/><br/></font><br/><br/><br/></td></tr>
	<tr><td width="50%" align=left style="border-width:thin; border-right-style:solid; ">Tgl kembali untuk proses: <br/>Diterima Oleh:<br/><br/><br/><br/><br/><br/></font></td>
	<td width="50%" align=left style="border-width:thin; "><font size="10pt">Tanggal selesai dari KK:<br/><br/><br/><br/><br/><br/></font></td></tr>
	</table>
	<font size="8pt" color="grey"><p>NB: Format Disposisi sesuai dengan PMK-181/PMK.01/2014 tentang Tata Naskah Dinas di Kementerian Keuangan</p></font>
	</body></html>';

$html	= ob_get_contents();
ob_end_clean();
$mpdf = new mPDF('utf-8','A4');
$mpdf->setFooter('Generated by: Aplikasi SPARTAN||');
$mpdf->WriteHTML(utf8_encode($html));
$mpdf->Output($nama_dokumen.".pdf",'I');
exit;
}
?>
