<?php

error_reporting(0);

$timezone = "Asia/Jakarta";
if(function_exists(date_default_timezone_set)) date_default_timezone_set($timezone);

session_start();
if (empty($_SESSION[username]) AND empty($_SESSION[passuser])){
  echo "<link href=style.css rel=stylesheet type=text/css>
 <center>Untuk mengakses modul, Anda harus login <br>";
  echo "<a href=../../index.php><b>LOGIN</b></a></center>";
}
else{
error_reporting(0);
include "../../plugin/mpdf/mpdf.php";
include "../../config/koneksi.php";

ob_start();

$nama 	= mysql_query("SELECT * from nama WHERE id_nama=1 ");
$tnama	= mysql_fetch_array($nama);

$kue	= mysql_query("Select a.nArsip,a.tArsip,a.jArsip,a.jKlasifikasi,b.jenis,a.bidang,a.rak,a.box,a.folder,a.baris,a.kolom,c.urbidang,substr(a.keterangan,1) as keterangan from sarsip as a left join rklasifikasi b on a.jKlasifikasi=b.kode left join rjabatan c on a.bidang=c.kode  where id_sArsip=$_GET[id] ");
$h		= mysql_fetch_array($kue);



echo '	
	<html>
	<head><title></title>
		<style type="text/css">	
	
	@page{
    margin-top: 0.25cm;
    margin-bottom: 0.25cm;
    margin-left: 0.25cm;
    margin-right: 0.25cm;
	}
	
	p{
		text-align:left;
		font-size:7px;
		font-family:"Times New Roman", Times, serif;
		color:#000066;
	}
	body{
		font-size:12px;
		font-family:"Times New Roman", Times, serif;	
	}
	
	table{
		border-style:solid;
		border-width:thin;
		border-spacing:inherit;
	}
	
	td{
		font-size:10px;
		font-family:"Times New Roman", Times, serif;	
	}
		
	</style>
	
	</head>
	<body>
	<table width="50%" cellspacing="0">
	<tr ><td style="border-width:thin; border-bottom-style:solid;" align="center" bgcolor="black"><font size=16px><b><font color="white">REGISTER ARSIP</font></b></font></td></tr>
	<tr ><td  style="border-width:thin; border-bottom-style:solid; font-size:10px;" align="center"><b>'.$tnama[nama].'</b></td></tr>
	</table>
	
	<table width="50%">
	<tr><td width="25%">Nomor Arsip</td><td width="2%">:</td><td>'.$h[nArsip].'</td></tr>
	<tr><td>Tgl. Registrasi</td><td>:</td><td>'.$h[tArsip].'</td></tr>
	<tr><td>Jenis Arsip</td><td>:</td><td>'.$h[jArsip].'</td></tr>
	<tr><td>Klasifikasi Arsip</td><td>:</td><td>'.$h[jKlasifikasi].'</td></tr>
	<tr><td></td><td></td><td>'.$h[jenis].'</td></tr>
	<tr><td>Unit Pengolah</td><td>:</td><td>'.$h[bidang].' - '.$h[urbidang].' </td></tr>		
	</tr>
	</table>
	
	<table width="50%" cellspacing="0">
	<tr>
	<td align="center" width="20%" style="border-width:thin; border-right-style:solid;" bgcolor="grey"><font color="white">Rak</font></td>
	<td align="center" width="20%" style="border-width:thin; border-right-style:solid;" bgcolor="grey"><font color="white">Box</font></td>
	<td align="center" width="20%" style="border-width:thin; border-right-style:solid;" bgcolor="grey"><font color="white">Folder</font></td>
	<td align="center" width="20%" bgcolor="grey"><font color="white">Baris</font></td>
	<td align="center" width="20%" style="border-width:thin; border-left-style:solid;" bgcolor="grey"><font color="white">Kolom</font></td>
	</tr>
	
	<tr>
	<td align="center" width="20%" style="border-width:thin; border-top-style:solid; border-right-style:solid;">'.$h[rak].'</td>
	<td align="center" width="20%" style="border-width:thin; border-top-style:solid; border-right-style:solid;">'.$h[box].'</td>
	<td align="center" width="20%" style="border-width:thin; border-top-style:solid; border-right-style:solid;">'.$h[folder].'</td>
	<td align="center" width="20%" style="border-width:thin; border-top-style:solid;">'.$h[baris].'</td>
	<td align="center" width="20%" style="border-width:thin; border-top-style:solid; border-left-style:solid;">'.$h[kolom].'</td>
	</tr>	
	</table>
	
	<table width="50%" cellspacing="0">
	<tr><td><b>Keterangan:</b></td></tr>
	<tr><td style="border-width:thin; border-bottom-style:solid;">'.$h[keterangan].'</td></tr><br/>	
	<tr><td align="center"><br/><img alt="barcode" src="barcode.php?text=*'.$h[nArsip].'*&print=true" /></td></tr>
	</table>	
	</body></html>';
	
$html	= ob_get_contents();
ob_end_clean();
$mpdf = new mPDF('utf-8','A4');
$mpdf->setFooter('Generated by: Aplikasi SPARTAN||');
$mpdf->WriteHTML(utf8_encode($html));
$mpdf->Output($nama_dokumen.".pdf",'I');
exit;
}	
?>

